version: '3.7'

services:
  hdfs-namenode:
    image: natbusa/hadoop:3.2.1
    command: hadoop-start.sh namenode
    ports:
    - 9870:9870
    networks:
    - databox
    volumes:
    - ./config:/opt/hadoop/etc/hadoop:ro
    - namenode:/var/lib/hadoop

  hdfs-datanode1:
    image: natbusa/hadoop:3.2.1
    command: hadoop-start.sh datanode
    networks:
    - databox
    volumes:
    - ./config:/opt/hadoop/etc/hadoop:ro
    - datanode1:/var/lib/hadoop

networks:
  databox:
    external: true

volumes:
  namenode:
  datanode1:
